---
driver: local

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  idempotency_test: true
  require_ansible_repo: false
  update_package_repos: false

verifier:
  name: inspec

suites:
  - name: default
