---
driver:
  name: <%= ENV['KITCHEN_DRIVER'] || 'vagrant' %>
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>
  require_chef_omnibus: false
  customize:
    memory: 256

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_ansible_repo: true
  ansible_version: <%= ENV['ANSIBLE_VERSION'] || 'latest' %>
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  idempotency_test: true
  update_package_repos: false

verifier:
  name: inspec

platforms:
  - name: <%= ENV['KITCHEN_PLATFORM'] || 'supertylerc/ansible-1.9' %>

suites:
  - name: default
