---
- name: Create Packer directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ packer_archive_path }}"
    - "{{ packer_binary_path }}"

- name: Download Packer
  get_url:
    url: "{{ packer_download_url }}"
    dest: "{{ packer_archive_path }}"
    force: "{{ packer_force_install }}"
  register: download

- name: Unpack Packer
  unarchive:
    src: "{{ packer_archive_path }}/{{ packer_download_url | basename }}"
    dest: "{{ packer_binary_path }}"
    copy: False
  when: download.changed

- name: Download Packer plugins
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ packer_binary_path }}/{{ item.key }}"
    force: "{{ packer_force_install }}"
  with_dict: packer_plugins

- name: Make Packer binaries executable
  file:
    path: "{{ item }}"
    state: file
    mode: 0755
  with_fileglob: "{{ packer_binary_path }}/packer*"
